### Register Testi (Kayıt Olma)
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "name": "Demo User",
    "email": "aiderece@gmail.com",
    "password": "1234567"
}

###

### Login Testi (Giriş Yapma)
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "omer@demo.com",
    "password": "1234567"
}

###

### Flowise Chat Proxy Testi
POST http://localhost:3000/chat/flowise
Content-Type: application/json

{
    "prompt": "Merhaba, bana kısa bir selam mesajı yaz.",
    "flowId": "c6f7f163-d503-4922-8557-b4ac4f2e78a7"
}
